amp: true
batch: 16
batch_size: 16
box: 7.5
cache: false
close_mosaic: 10
cls: 0.5
copy_paste: 0.0
cos_lr: false
degrees: 10.0
deterministic: true
device: cuda
dfl: 1.5
dropout: 0.0
epochs: 400
exist_ok: true
fl_gamma: 0.0
fliplr: 0.5
flipud: 0.0
freeze_backbone: false
freeze_layers: 0
half: false
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
imgsz: 640
label_smoothing: 0.0
lr0: 0.008
lrf: 0.01
mask_ratio: 4
mixup: 0.1
model_size: yolo11m
momentum: 0.937
mosaic: 1.0
name: traffic_light_detection
nosave: false
noval: false
optimizer: SGD
overlap_mask: true
patience: 50
perspective: 0.0
plots: true
pretrained: true
project: experiments
rect: false
resume: false
save: true
save_period: 10
scale: 0.5
seed: 42
shear: 0.0
single_cls: false
translate: 0.1
val: true
verbose: true
warmup_bias_lr: 0.1
warmup_epochs: 5.0
warmup_momentum: 0.8
weight_decay: 0.0005
workers: 8
